foreground #dcd7ba
background #1f1f28
selection_foreground #dcd7ba
selection_background #363646

cursor #dcd7ba
cursor_text_color #1f1f28

active_border_color #dcd7ba
active_tab_background #dcd7ba

color0 #1f1f28
color1 #c34043
color2 #76946a
color3 #c0a36e
color4 #7e9cd8
color5 #957fb8
color6 #6a9589
color7 #dcd7ba
color8 #54546D
color9 #e82424
color10 #98bb6c
color11 #e6c384
color12 #7fb4ca
color13 #938aa9
color14 #7aa89f
color15 #dcd7ba

#Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
background_opacity 0.8
font_size 9.0

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
