#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_COURSE[0]}") && pwd)

echo "$XDG_CONFIG_HOME"
echo "$script_dir"
dry="0"

while [[ $# > 0 ]]; do 
    if [[ $1 == "--dry" ]]; then 
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi

}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return 
    fi 
    "$@"
}

log "----------------- dev-env ----------------"
 
cd $script_dir
copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do 
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir 
    done 
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    
    if [ ! -f "$from" ]; then
        echo "Warning: Source file $from doesn't exist."
 	# Create empty file at destination if needed
	mkdir -p "$to"
	touch "$to/$name"
	echo "Create empty file at $to/$name"
	return
    fi

    # Remove destination file if it exists
    if [ -f "$to/$name" ]; then
        execute rm "$to/$name"
    fi

    # Copy the file
    execute cp "$from" "$to/$name"
    echo "Copied $from to $to/$name"

}

echo "$XDG_CONFIG_HOME"
echo "dev-env path:$DEV_ENV"
DEV_ENV=$HOME/dev
echo $DEV_ENV
copy_dir $DEV_ENV/env/.config $XDG_CONFIG_HOME
copy_dir $DEV_ENV/env/.local $HOME/.local

copy_file $DEV_ENV/env/.zshrc $HOME
copy_file $DEV_ENV/env/.zsh_profile $HOME
copy_file $DEV_ENV/dev-env $HOME/.local/scripts



