#!/usr/bin/env bash

# Clone Neovim v0.10.4
git clone -b v0.10.4 https://github.com/neovim/neovim.git "$HOME/personal/packages/neovim"

# Install build dependencies
sudo pacman -S --needed base-devel cmake gettext lua51 lua51-lpeg lua51-mpack lua51-bitop
sudo pacman -S lua luarocks

# Create directory if it doesn't exist
mkdir -p "$HOME/personal/neovim"

# Navigate to the project directory
cd "$HOME/personal/neovim"

# Build Neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo

# Install Neovim
sudo make install

