#!/usr/bin/env bash

sudo apt install nodejs npm
npm config set prefix ~/.local/npm
npm i -g n
n lts

curl -fsSL https://deno.land/install.sh | sh
curl -fsSL https://bun.sh/install | bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

